website/templates/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__) # initializing flask. 
    app.config['SECRET_KEY'] = 'asdf;lkj' # encrypts the cookies and session data

    return app

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from . import db
import json
from .components.dropdownDogBreedInfo import get_dropdown_menu
from .models import Note, Dogs, Trainer
from .components.filterTrainer import fetch_filtered_trainers, trainer_names, training_types, sizes, experiences, cities

import random





# Function to generate 50 fake dog trainer datas
def generate_fake_trainers():
    # from .models import Trainer # Importing Trainer model here to avoid circular import
 
    fake_trainers = []
    for name in (trainer_names): 
        training_type = random.choice(training_types)
        size = random.choice(sizes)["value"]  # Extract the value from the size dictionary
        experience = random.choice(experiences)["value"]  # Extract the value from the experience dictionary
        city = random.choice(cities)

        trainer = Trainer(name=name, training_type=training_type, size=size, experience=experience, city=city)
        fake_trainers.append(trainer)

    # Add the fake trainers to the database and commit the changes
    db.session.bulk_save_objects(fake_trainers)
    db.session.commit()

    return fake_trainers






# Blueprint helps split and organize our view file.
views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():

    if request.method == 'POST': 
        note = request.form.get('note')#Gets the note from the HTML 
        
        if len(note) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(data=note, user_id=current_user.id)  #providing the schema for the note 
            db.session.add(new_note) #adding the note to the database 
            db.session.commit()
            flash('Note added!', category='success')
        
        # Redirect the user to another route (e.g., /notes) after successful POST
        return redirect(url_for('views.home'))
    notes = Note.query.filter_by(user_id=current_user.id).all()
    return render_template("home.html", notes=notes, user=current_user)


@views.route('/delete-note', methods=['POST'])
@login_required
def delete_note():  

    note = json.loads(request.data) # grabs the string as JSON from the INDEX.js file and turns it into python dictionary object
    noteId = note['noteId'] # Then we can access the noteId.
    note = Note.query.get(noteId)

    if note and note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
            print("note deleted successfully")
            flash('Note deleted!', category='success')
    return jsonify({}) 


@views.route('/delete-dog', methods=['POST'])
@login_required
def delete_dog():  

    dog = json.loads(request.data) # this function expects a JSON from the INDEX.js file 
    dogID = dog['dogID']
    dog = Dogs.query.get(dogID)

    if dog and dog.user_id == current_user.id:
            db.session.delete(dog)
            db.session.commit()
            flash('dog deleted!', category='success')
    return jsonify({})



@views.route('/training', methods=['GET', 'POST'])
@login_required
def training():

    if request.method == 'POST':
        dog_name = request.form.get('dog_name')
        dog_image = request.form.get('dog_image')

        if len(dog_name) < 1:
            flash('Dog name must be greater than 1 character.', category='error')

        elif len(dog_name) > 12:
            flash('Dog name must be less than 12 characters', category='error')

        elif not dog_image:
            flash('You must pick a dog breed.', category='error')

        else:
        # Save the selected dog information to the logged-in user
            new_dog_info = Dogs(dog_name=dog_name, dog_image=dog_image, user_id=current_user.id)
            db.session.add(new_dog_info)
            db.session.commit()
            flash('Dog registration successful!', category='success')
            return redirect(url_for('views.training'))
        
    dogs = Dogs.query.filter_by(user_id=current_user.id).all()

    return render_template("training.html", user=current_user, get_dropdown_menu=get_dropdown_menu, dogs=dogs)


@views.route('/about', methods=['GET', 'POST'])
def about():
    
    return render_template("about.html", user=current_user)




#######


@views.route('/search-trainer', methods=['GET', 'POST'])
@login_required
def search():
    if request.method == 'POST':
        # Get the selected criteria from the form submission
        training_type = request.form.get('training_type')
        size = request.form.get('size')
        experience = request.form.get('experience')
        city = request.form.get('city')
    else:
        # If it's an initial GET request, use the query parameters from the URL
        training_type = request.args.get('training_type')
        size = request.args.get('size')
        experience = request.args.get('experience')
        city = request.args.get('city')

    # from .components.filterTrainer import fetch_filtered_trainers
    # Fetch the filtered trainers based on the selected filters
    filtered_trainers = fetch_filtered_trainers(training_type, size, experience, city)

    return render_template(
        "searchTrainer.html",
        filtered_trainers=filtered_trainers,
        training_types=training_types,
        sizes=sizes,
        experiences=experiences,
        cities=cities,
        selected_training_type=training_type,  
        selected_size=size,
        selected_experience=experience,
        selected_city=city,
        user=current_user
    )

website/templates/about.html
{% extends "base.html" %} {% block title %}About{% endblock %} 

{% block content %}
<div class="">
    <img class="about-container" src="../static/assets/a-about2.jpg" alt="">
</div>
<h3 align="center">About Pupcademy!</h3>
<main class="about-main">
    <p>
        Welcome to our online dog training program! At our center, we're dedicated to providing your beloved dogs with engaging activities that promote both physical and mental well-being. Through a variety of puzzles, games, and exercises, we aim to build their confidence, improve body awareness, enhance problem-solving skills, and reinforce positive behavior.
    </p>
    <p>
        In our virtual training sessions, dogs will learn valuable conflict resolution skills as they are encouraged to develop 'plan B' or 'plan C' strategies when faced with challenges. Our approach encourages them to think, sniff, dig, run, jump, and socialize in safe and appropriate ways.
    </p>
    <p>
        We focus on teaching settling techniques, promoting calm behavior, and lowering arousal levels. Our training also emphasizes the importance of manners, helping your dogs learn to share space with others and communicate effectively with fellow canines. Positive reinforcement is at the core of our methods, rewarding them for working harmoniously alongside other dogs.
    </p>
    <p>
        Throughout our program, we strive to expose your dogs to a wide range of new experiences, from different smells and tastes to diverse sights and textures. These opportunities contribute to building their confidence, enriching their days, expanding their minds, and strengthening their bodies.
    </p>
    <p>
        Join us today and embark on a rewarding journey of online dog training, where your furry friends will thrive in the comfort of their own homes while gaining essential skills for a fulfilling and enriched life.
    </p>
</main>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link
			rel="stylesheet"
			href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
			integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
			crossorigin="anonymous"
		/>
		<link
			rel="stylesheet"
			href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
			crossorigin="anonymous"
		/>
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">


		<title>{% block title %}Home{% endblock %}</title>
	</head>
	<body>
		<!-- Navbar -->
		<nav class="navbar navbar-expand-lg " style="background-color: #c3e1f7;">
			<button
				class="navbar-toggler"
				type="button"
				data-toggle="collapse"
				data-target="#navbar"
			>
				<a class="navbar-brand" href="#">
					<img src="../static/assets/a-chat-icon.png" alt="" width="30" height="30" class="d-inline-block align-text-top">
					Menu
				</a>
			</button>
			<div class="collapse navbar-collapse " id="navbar">
				<div class="navbar-nav font-custom-color">
					{% if user.is_authenticated %}
					<a class="nav-item nav-link" id="home" href="/">Home</a>
					<a class="nav-item nav-link" id="about" href="/about">About Pupcademy</a>
					<a class="nav-item nav-link" id="training" href="/training">Training</a>
					<a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
					{% else %}
					<a class="nav-item nav-link" id="login" href="/login">Login</a>
					<a class="nav-item nav-link" id="about" href="/about">About Pupcademy</a>
					<a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
					{% endif %}
				</div>
			</div>
		</nav>

		<!-- FLASH MESSAGE -->
		{% with messages = get_flashed_messages(with_categories=true) %} {% if
		messages %} {% for category, message in messages %} {% if category ==
		'error' %}
		<div class="alert alert-danger alter-dismissable fade show" role="alert">
			{{ message }}
			<button type="button" class="close btn-close-color" data-dismiss="alert">
				<span aria-hidden="true">&#x2718;</span>
			</button>
		</div>
		{% else %}
		<div class="alert alert-success alter-dismissable fade show" role="alert">
			{{ message }}
			<button type="button" class="close btn-close-color" data-dismiss="alert">
				<span aria-hidden="true">&#x2718;</span>
			</button>
		</div>
		{% endif %} {% endfor %} {% endif %} {% endwith %}

		<div class="container">{% block content %} {% endblock %}</div>
		
		<script
			src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
			integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
			crossorigin="anonymous"
		></script>
		<script
			src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
			integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
			crossorigin="anonymous"
		></script>
		<script
			src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
			integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
			crossorigin="anonymous"
		></script>

		
{% block javascript %}
		<script src="{{ url_for('static', filename='flashMessageTimer.js') }}"></script>
		<script src="{{ url_for('static', filename='dropdownUpdateButton.js') }}"></script>
		<script src="{{ url_for('static', filename='deleteFromDB.js') }}"></script>

{% endblock %}

	</body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 

{% block content %}
<h1 align="center">Welcome back, {{user.first_name}}.</h1>
<br>
<h3 align="center">Training Notes</h3>
<ul class="list-group list-group-flush" id="notes">

	{% for note in user.notes %}
	<li class="list-group-item">
		{{ note.data }}

		<button type="button" class="close btn-close-color" onClick="deleteNote({{ note.id }})">
			<span aria-hidden="true">&#x2718;</span>
		</button>
	</li>
	{% endfor %}

</ul>

<form method="POST">
	<textarea name="note" id="note" class="form-control"></textarea>
	<br />

	<div align="center">
		<button type="submit" class="btn btn-custom-color">Add Note</button>
	</div>
	
</form>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} 

{% block content %}
<form method="POST">
	<h3 align="center">Login</h3>
	<div class="form-group">
		<label for="email">Email Address</label>
		<input
			type="email"
			class="form-control"
			id="email"
			name="email"
			placeholder="Enter email"
		/>
	</div>
	<div class="form-group">
		<label for="password">Password</label>
		<input
			type="password"
			class="form-control"
			id="password"
			name="password"
			placeholder="Enter password"
		/>
	</div>
	<br />
	<button type="submit" class="btn btn-custom-color">Login</button>
</form>
		
{% endblock %}

website/templates/searchTrainer.html
{% extends "base.html" %}

{% block title %}Search-Trainer{% endblock %}

{% block content %}
    <form method="post" action="{{ url_for('views.search') }}">
        <label for="training_type">Training Type:</label>
        <select id="training_type" name="training_type">
            <option value="">All</option>
            {% for type in training_types %}
                <option value="{{ type }}" {% if selected_training_type == type %}selected{% endif %}>{{ type }}</option>
            {% endfor %}
        </select>

        <label for="size">Size:</label>
        <select id="size" name="size">
            <option value="">All</option>
            {% for size_item in sizes %}
                <option value="{{ size_item.value }}" {% if selected_size == size_item.value %}selected{% endif %}>{{ size_item.text }}</option>
            {% endfor %}
        </select>

        <label for="experience">Experience:</label>
        <select id="experience" name="experience">
            <option value="">All</option>
            {% for experience_item in experiences %}
                <option value="{{ experience_item.value }}" {% if selected_experience == experience_item.value %}selected{% endif %}>{{ experience_item.text }}</option>
            {% endfor %}
        </select>

        <label for="city">City:</label>
        <select id="city" name="city">
            <option value="">All</option>
            {% for city_item in cities %}
                <option value="{{ city_item }}" {% if selected_city == city_item %}selected{% endif %}>{{ city_item }}</option>
            {% endfor %}
        </select>

        <button type="submit">Apply Filters</button>
    </form>

    <div class="search-results">
        {% if filtered_trainers %}
            <h3>Search Results:</h3>
            <ul>
                {% for trainer in filtered_trainers %}
                    <li>{{ trainer.name }} - {{ trainer.training_type }} - {{ trainer.size }} - {{ trainer.experience }} - {{ trainer.city }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No trainers found matching your criteria.</p>
        {% endif %}
    </div>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} 

{% block content %}
<form method="POST">
	<h3 align="center">Sign Up</h3>
	<div class="form-group">
		<label for="email">Email Address</label>
		<input
			type="email"
			class="form-control"
			id="email"
			name="email"
			placeholder="Enter email"
		/>
	</div>
	<div class="form-group">
		<label for="firstName">First Name</label>
		<input
			type="text"
			class="form-control"
			id="firstName"
			name="firstName"
			placeholder="Enter first name"
		/>
	</div>
	<div class="form-group">
		<label for="password1">Password</label>
		<input
			type="password"
			class="form-control"
			id="password1"
			name="password1"
			placeholder="Enter password"
		/>
	</div>
	<div class="form-group">
		<label for="password2">Password (Confirm)</label>
		<input
			type="password"
			class="form-control"
			id="password2"
			name="password2"
			placeholder="Confirm password"
		/>
	</div>
	<br />
	<button type="submit" class="btn btn-custom-color">Submit</button>
</form>
{% endblock %}

website/templates/training.html
{% extends "base.html" %} {% block title %}Training{% endblock %}

{% block content %}
<h3 align="center">{{user.first_name}}, Who will you train today?</h3>
<br>
<div id="selectedDog" align="center">
	<ul class="" id="dogList">
		{% if dogs %}
			{% for dog in dogs %}
				<li class="list-group-item">
					<a href="/search-trainer" class="dog-info">
						<img src="{{ dog.dog_image }}" alt="" width="100" height="100">
						<h4>{{ dog.dog_name }}</h4>
					</a>
					<button type="button" class="close btn-close-color" onClick="deleteDog({{ dog.id }})">
						<span aria-hidden="true">&#x2718;</span>
					</button>
				</li>
			{% endfor %}
		{% else %}
			<h5>No dogs registered</h5>
		{% endif %}
	</ul>
</div>

<br>

<form method="POST" id="registerDogForm" onsubmit="saveSelectedDog(event)">  
	<h3 align="center">Register Your Dog</h3>

	<div class="form-group">
		<label for="dog_name">Dog Name</label>
		<input
			type="text"
			class="form-control"
			id="dog_name"
			name="dog_name"
			placeholder="Enter dog name"
		/>
	</div>
	<div class="form-group">
		<div class="container mt-3">
			<!-- dropdown dob breed info pulled from js file in components -->
			{{ get_dropdown_menu() | safe }}
		</div>
	</div>
	<br />
	
	<!-- Add hidden inputs here -->
	<input type="hidden" id="dogNameInput" name="dog_name" value="">
	<input type="hidden" id="dogImageInput" name="dog_image" value="">
	<button type="submit" class="btn btn-custom-color">Register</button>
</form>

{% endblock %}